bundler_args: --without development
before_install: git checkout -b test
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-19mode
  - jruby-head
  - rbx
matrix:
  allow_failures:
    - rvm: ruby-head
