before_install:
  - echo "require 'rbconfig'; Config=RbConfig unless defined? Config" > /tmp/fix_rbconfig.rb
env:
  - RUBYOPT=-r/tmp/fix_rbconfig.rb
bundler_args: --without development
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-18mode
  - rbx-19mode
matrix:
  allow_failures:
    - rvm: jruby-19mode
